apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-frontend-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: bookstore-frontend
  template:
    metadata:
      labels:
        app: bookstore-frontend
    spec:
      containers:
        - name: bookstore-frontend-container
          image: mehedibu2013/bookstore-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-backend-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: bookstore-backend
  template:
    metadata:
      labels:
        app: bookstore-backend
    spec:
      containers:
        - name: bookstore-backend-container
          image: mehedibu2013/bookstore-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5555
          env:
            - name: MONGODB_URI
              value: "mongodb+srv://admin765:admin@cluster0.sbyfstw.mongodb.net/book-collection?retryWrites=true&w=majority&appName=Cluster0"
            - name: PORT
              value: "5555"
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-frontend-service
spec:
  type: NodePort
  selector:
    app: bookstore-frontend
  ports:
    - port: 80
      targetPort: 5173
      nodePort: 31080  # ✅ valid NodePort range
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-backend-service
spec:
  type: NodePort
  selector:
    app: bookstore-backend
  ports:
    - port: 5555
      targetPort: 5555
      nodePort: 30055  # ✅ valid NodePort range
